/**
 * load_seed_patched.js
 * Loads data from seed_patched.sql into DB via Prisma (handles camelCase columns)
 */
require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function run() {
  // ── Clear ──────────────────────────────────────────────────────────────────
  await prisma.constraintViolationLog.deleteMany({});
  await prisma.scheduleVersion.deleteMany({});
  await prisma.schedule.deleteMany({});
  await prisma.teachingUnit.deleteMany({});
  await prisma.assignment.deleteMany({});
  await prisma.curriculum.deleteMany({});
  await prisma.classGroup.deleteMany({});
  await prisma.cohort.deleteMany({});
  await prisma.major.deleteMany({});
  await prisma.subject.deleteMany({});
  await prisma.room.deleteMany({});
  await prisma.location.deleteMany({});
  await prisma.teacher.deleteMany({});
  await prisma.user.deleteMany({});
  console.log('✓ Cleared');

  // 1. LOCATIONS
  await prisma.location.createMany({ data: [
    { id:'loc_a17',  name:'Nhà học A17',      code:'A17',  address:'17 Tạ Quang Bửu, Hai Bà Trưng, Hà Nội' },
    { id:'loc_pm',   name:'Nhà học PM',       code:'PM',   address:'75 Phương Mai, Đống Đa, Hà Nội' },
    { id:'loc_b4',   name:'Nhà học B4',       code:'B4',   address:'Ngõ 15 Tạ Quang Bửu, Hai Bà Trưng, Hà Nội' },
    { id:'loc_d',    name:'Nhà học D',        code:'D',    address:'92A Lê Thanh Nghị, Hai Bà Trưng, Hà Nội' },
    { id:'loc_c4b',  name:'Nhà C4B (ĐHBKHN)', code:'C4B',  address:'Trong trường ĐHBK Hà Nội' },
    { id:'loc_th1a', name:'Khu TH 1A',        code:'TH1A', address:'Ngõ 17 Tạ Quang Bửu, Hai Bà Trưng, Hà Nội' },
  ]});
  console.log('✓ locations (6)');

  // 2. ROOMS
  await prisma.room.createMany({ data: [
    { id:'room_a17_401', locationId:'loc_a17', code:'A17-401', type:'THEORY',   capacity:50 },
    { id:'room_a17_402', locationId:'loc_a17', code:'A17-402', type:'THEORY',   capacity:50 },
    { id:'room_a17_403', locationId:'loc_a17', code:'A17-403', type:'THEORY',   capacity:50 },
    { id:'room_a17_404', locationId:'loc_a17', code:'A17-404', type:'THEORY',   capacity:50 },
    { id:'room_a17_405', locationId:'loc_a17', code:'A17-405', type:'THEORY',   capacity:50 },
    { id:'room_a17_406', locationId:'loc_a17', code:'A17-406', type:'THEORY',   capacity:50 },
    { id:'room_a17_407', locationId:'loc_a17', code:'A17-407', type:'THEORY',   capacity:50 },
    { id:'room_a17_408', locationId:'loc_a17', code:'A17-408', type:'THEORY',   capacity:50 },
    { id:'room_a17_409', locationId:'loc_a17', code:'A17-409', type:'THEORY',   capacity:50 },
    { id:'room_a17_501a',locationId:'loc_a17', code:'A17-501A',type:'THEORY',   capacity:60 },
    { id:'room_a17_501b',locationId:'loc_a17', code:'A17-501B',type:'THEORY',   capacity:60 },
    { id:'room_a17_502', locationId:'loc_a17', code:'A17-502', type:'THEORY',   capacity:50 },
    { id:'room_a17_504', locationId:'loc_a17', code:'A17-504', type:'THEORY',   capacity:50 },
    { id:'room_pm_301',  locationId:'loc_pm',  code:'PM-301',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_302',  locationId:'loc_pm',  code:'PM-302',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_303',  locationId:'loc_pm',  code:'PM-303',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_304',  locationId:'loc_pm',  code:'PM-304',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_305',  locationId:'loc_pm',  code:'PM-305',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_306',  locationId:'loc_pm',  code:'PM-306',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_401',  locationId:'loc_pm',  code:'PM-401',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_402',  locationId:'loc_pm',  code:'PM-402',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_403',  locationId:'loc_pm',  code:'PM-403',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_404',  locationId:'loc_pm',  code:'PM-404',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_405',  locationId:'loc_pm',  code:'PM-405',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_406',  locationId:'loc_pm',  code:'PM-406',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_407',  locationId:'loc_pm',  code:'PM-407',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_408',  locationId:'loc_pm',  code:'PM-408',  type:'PRACTICE', capacity:40 },
    { id:'room_pm_409',  locationId:'loc_pm',  code:'PM-409',  type:'PRACTICE', capacity:40 },
    { id:'room_b4_301',  locationId:'loc_b4',  code:'B4-301',  type:'PRACTICE', capacity:40 },
    { id:'room_d_303',   locationId:'loc_d',   code:'D-303',   type:'PRACTICE', capacity:40 },
    { id:'room_c4b_1',   locationId:'loc_c4b', code:'C4B-1',   type:'THEORY',   capacity:80 },
    { id:'room_c4b_2',   locationId:'loc_c4b', code:'C4B-2',   type:'THEORY',   capacity:80 },
    { id:'room_c4b_3',   locationId:'loc_c4b', code:'C4B-3',   type:'THEORY',   capacity:80 },
    { id:'room_c4b_4',   locationId:'loc_c4b', code:'C4B-4',   type:'THEORY',   capacity:80 },
    { id:'room_c4b_5',   locationId:'loc_c4b', code:'C4B-5',   type:'THEORY',   capacity:80 },
    { id:'room_c4b_6',   locationId:'loc_c4b', code:'C4B-6',   type:'THEORY',   capacity:80 },
  ]});
  console.log('✓ rooms (36)');

  // 3. TEACHERS
  await prisma.teacher.createMany({ data: [
    { id:'gv_cuong',      name:'Thầy Cường',       code:'GV001', email:'cuong@school.edu.vn',       dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_binh_cuong', name:'Cô Bích',           code:'GV002', email:'bich@school.edu.vn',        dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_han',        name:'Cô Hân',            code:'GV003', email:'han@school.edu.vn',         dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_muoi',       name:'Cô Mười Phương',    code:'GV004', email:'muoiphuong@school.edu.vn',  dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_trung',      name:'Thầy Trung',        code:'GV005', email:'trung@school.edu.vn',       dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_tung_ct',    name:'Thầy Công Tùng',    code:'GV006', email:'congtung@school.edu.vn',    dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_tung_ng',    name:'Thầy Nguyễn Tùng',  code:'GV007', email:'nguyentung@school.edu.vn',  dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_hoa',        name:'Cô Hoa',            code:'GV008', email:'hoa@school.edu.vn',         dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_uy',         name:'Thầy Uy',           code:'GV009', email:'uy@school.edu.vn',          dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_toan',       name:'Thầy Toàn',         code:'GV010', email:'toan@school.edu.vn',        dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_loi_lt',     name:'Thầy Lợi',          code:'GV011', email:'loi@school.edu.vn',         dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_quoc_tuan',  name:'Thầy Quốc Tuấn',    code:'GV012', email:'quoctuan@school.edu.vn',    dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_ho_tung',    name:'Thầy Hồ Tùng',      code:'GV013', email:'hotung@school.edu.vn',      dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_van_pt',     name:'Cô Vân',            code:'GV014', email:'van@school.edu.vn',         dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_linh_cq',    name:'Cô Linh',           code:'GV015', email:'linh@school.edu.vn',        dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_thanh_tung', name:'Cô Thanh Tùng',     code:'GV016', email:'thanhtung@school.edu.vn',   dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_quoc',       name:'Thầy Quốc',         code:'GV017', email:'quoc@school.edu.vn',        dept:'CNTT',  unavailableSlots:[] },
    { id:'gv_phuong_dt',  name:'Thầy D.T. Phương',  code:'GV018', email:'dtphuong@school.edu.vn',    dept:'ĐTCN',  unavailableSlots:[] },
    { id:'gv_tien_dt',    name:'Thầy Tiến',         code:'GV019', email:'tiendt@school.edu.vn',      dept:'ĐTCN',  unavailableSlots:[] },
    { id:'gv_huong_dt',   name:'Cô Hương',          code:'GV020', email:'huongdt@school.edu.vn',     dept:'ĐTCN',  unavailableSlots:[] },
    { id:'gv_long_dt',    name:'Thầy Long',         code:'GV021', email:'longdt@school.edu.vn',      dept:'ĐTCN',  unavailableSlots:[] },
    { id:'gv_thinh',      name:'Thầy Thịnh',        code:'GV022', email:'thinh@school.edu.vn',       dept:'ĐTCN',  unavailableSlots:[] },
    { id:'gv_duc_md',     name:'Thầy N.M.Đức',      code:'GV023', email:'nmduc@school.edu.vn',       dept:'ĐTCN',  unavailableSlots:[] },
    { id:'gv_lien_dcn',   name:'Cô Liên',           code:'GV024', email:'lien@school.edu.vn',        dept:'ĐCN',   unavailableSlots:[] },
    { id:'gv_long_dcn',   name:'Thầy M.Long',       code:'GV025', email:'mlong@school.edu.vn',       dept:'ĐCN',   unavailableSlots:[] },
    { id:'gv_sang',       name:'Thầy Sang',         code:'GV026', email:'sang@school.edu.vn',        dept:'ĐCN',   unavailableSlots:[] },
    { id:'gv_mui',        name:'Cô Mùi',            code:'GV027', email:'mui@school.edu.vn',         dept:'ĐCN',   unavailableSlots:[] },
    { id:'gv_sy',         name:'Thầy Sỹ',           code:'GV028', email:'sy@school.edu.vn',          dept:'ĐCN',   unavailableSlots:[] },
    { id:'gv_tuyen',      name:'Thầy Tuyến',        code:'GV029', email:'tuyen@school.edu.vn',       dept:'ĐCN',   unavailableSlots:[] },
    { id:'gv_cuong_tg',   name:'Thầy Cường TG',     code:'GV030', email:'cuongtg@school.edu.vn',     dept:'ĐCN',   unavailableSlots:[] },
    { id:'gv_huong_ck',   name:'Thầy Hường',        code:'GV031', email:'huongck@school.edu.vn',     dept:'OTO',   unavailableSlots:[] },
    { id:'gv_lam',        name:'Thầy Lâm',          code:'GV032', email:'lam@school.edu.vn',         dept:'OTO',   unavailableSlots:[] },
    { id:'gv_tien_dung',  name:'Thầy Tiến Dũng',    code:'GV033', email:'tiendung@school.edu.vn',    dept:'OTO',   unavailableSlots:[] },
    { id:'gv_thang',      name:'Thầy Thắng',        code:'GV034', email:'thang@school.edu.vn',       dept:'OTO',   unavailableSlots:[] },
    { id:'gv_binh_oto',   name:'Thầy Bình',         code:'GV035', email:'binhoto@school.edu.vn',     dept:'OTO',   unavailableSlots:[] },
    { id:'gv_thanh_ct',   name:'Cô Thanh',          code:'GV036', email:'thanhct@school.edu.vn',     dept:'DC',    unavailableSlots:[{dayOfWeek:6,periodStart:1,periodEnd:6}] },
    { id:'gv_ngoc',       name:'Cô Ngọc',           code:'GV037', email:'ngoc@school.edu.vn',        dept:'DC',    unavailableSlots:[] },
    { id:'gv_lan_ct',     name:'Cô Lan',            code:'GV038', email:'lanct@school.edu.vn',       dept:'DC',    unavailableSlots:[] },
    { id:'gv_huyen',      name:'Cô Huyền',          code:'GV039', email:'huyen@school.edu.vn',       dept:'TA',    unavailableSlots:[] },
    { id:'gv_ninh_ha',    name:'Cô Ninh Hà',        code:'GV040', email:'ninhha@school.edu.vn',      dept:'TA',    unavailableSlots:[] },
    { id:'gv_quynh_anh',  name:'Cô Quỳnh Anh',      code:'GV041', email:'quynhanh@school.edu.vn',    dept:'TA',    unavailableSlots:[] },
    { id:'gv_dung_toan',  name:'Thầy Dũng',         code:'GV042', email:'dungtoan@school.edu.vn',    dept:'DC',    unavailableSlots:[] },
    { id:'gv_sam',        name:'Cô Sâm',            code:'GV043', email:'sam@school.edu.vn',         dept:'DC',    unavailableSlots:[] },
    { id:'gv_thao',       name:'Cô Thảo',           code:'GV044', email:'thao@school.edu.vn',        dept:'DC',    unavailableSlots:[] },
    { id:'gv_anh_tkdh',   name:'Cô Ánh',            code:'GV045', email:'anhtkdh@school.edu.vn',     dept:'TKĐH',  unavailableSlots:[] },
    { id:'gv_nhung',      name:'Cô Nhung',          code:'GV046', email:'nhung@school.edu.vn',       dept:'TKĐH',  unavailableSlots:[] },
    { id:'gv_trang',      name:'Cô Trang',          code:'GV047', email:'trang@school.edu.vn',       dept:'TKĐH',  unavailableSlots:[] },
    { id:'gv_quang_tkdh', name:'Thầy Quang',        code:'GV048', email:'quangtkdh@school.edu.vn',   dept:'TKĐH',  unavailableSlots:[] },
    { id:'gv_thanh_tkdh', name:'Thầy Thành',        code:'GV049', email:'thanhtkdh@school.edu.vn',   dept:'TKĐH',  unavailableSlots:[] },
    { id:'gv_loi_tkdh',   name:'Thầy Lợi TKĐH',     code:'GV050', email:'loitkdh@school.edu.vn',     dept:'TKĐH',  unavailableSlots:[] },
  ]});
  console.log('✓ teachers (50)');

  // 4. MAJORS
  await prisma.major.createMany({ data: [
    { id:'major_ltmt',  code:'LTMT',  name:'Lập trình máy tính' },
    { id:'major_qtm',   code:'QTM',   name:'Quản trị mạng máy tính' },
    { id:'major_udpm',  code:'UDPM',  name:'Ứng dụng phần mềm' },
    { id:'major_tkdh',  code:'TKĐH',  name:'Thiết kế đồ họa' },
    { id:'major_oto',   code:'OTO',   name:'Công nghệ ô tô' },
    { id:'major_cdt',   code:'CĐT',   name:'Công nghệ điều tử' },
    { id:'major_dcn',   code:'ĐCN',   name:'Điện công nghiệp' },
    { id:'major_tdh',   code:'TĐH',   name:'Tự động hóa' },
    { id:'major_dtcn',  code:'ĐTCN',  name:'Điện tử công nghiệp' },
    { id:'major_cnctm', code:'CNCTM', name:'Công nghệ cắt gọt kim loại' },
    { id:'major_ktml',  code:'KTML',  name:'Kỹ thuật máy lạnh' },
    { id:'major_ddd',   code:'ĐDD',   name:'Điện dân dụng' },
    { id:'major_tmdt',  code:'TMĐT',  name:'Thương mại điện tử' },
    { id:'major_qtdn',  code:'QTDN',  name:'Quản trị doanh nghiệp' },
    { id:'major_ktdn',  code:'KTDN',  name:'Kế toán doanh nghiệp' },
  ]});
  console.log('✓ majors (15)');

  // 5. COHORTS
  await prisma.cohort.createMany({ data: [
    { id:'cohort_k15', code:'K15', year:2022 },
    { id:'cohort_k16', code:'K16', year:2023 },
    { id:'cohort_k17', code:'K17', year:2024 },
  ]});
  console.log('✓ cohorts');

  // 6. CLASS GROUPS
  await prisma.classGroup.createMany({ data: [
    { id:'cls_ltmt1',    majorId:'major_ltmt', cohortId:'cohort_k15', code:'LTMT1-K15',    studentCount:38 },
    { id:'cls_ltmt2',    majorId:'major_ltmt', cohortId:'cohort_k15', code:'LTMT2-K15',    studentCount:38 },
    { id:'cls_ltmt3',    majorId:'major_ltmt', cohortId:'cohort_k15', code:'LTMT3-K15',    studentCount:36 },
    { id:'cls_ltmt4',    majorId:'major_ltmt', cohortId:'cohort_k15', code:'LTMT4-K15',    studentCount:36 },
    { id:'cls_ltmt5',    majorId:'major_ltmt', cohortId:'cohort_k15', code:'LTMT5-K15',    studentCount:35 },
    { id:'cls_ltmt6',    majorId:'major_ltmt', cohortId:'cohort_k15', code:'LTMT6-K15',    studentCount:35 },
    { id:'cls_qtm1',     majorId:'major_qtm',  cohortId:'cohort_k15', code:'QTM1-K15',     studentCount:40 },
    { id:'cls_udpm1',    majorId:'major_udpm', cohortId:'cohort_k15', code:'ƯDPM1-K15',    studentCount:38 },
    { id:'cls_udpm2',    majorId:'major_udpm', cohortId:'cohort_k15', code:'ƯDPM2-K15',    studentCount:38 },
    { id:'cls_tkdh1',    majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH1-K15',    studentCount:36 },
    { id:'cls_tkdh2',    majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH2-K15',    studentCount:36 },
    { id:'cls_tkdh3',    majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH3-K15',    studentCount:35 },
    { id:'cls_tkdh4',    majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH4-K15',    studentCount:35 },
    { id:'cls_tkdh5',    majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH5-K15',    studentCount:34 },
    { id:'cls_tkdh6',    majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH6-K15',    studentCount:34 },
    { id:'cls_tkdh7',    majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH7-K15',    studentCount:33 },
    { id:'cls_tkdh_clc', majorId:'major_tkdh', cohortId:'cohort_k15', code:'TKĐH CLC-K15', studentCount:30 },
    { id:'cls_oto1',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 1-K15',   studentCount:38 },
    { id:'cls_oto2',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 2-K15',   studentCount:38 },
    { id:'cls_oto3',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 3-K15',   studentCount:38 },
    { id:'cls_oto4',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 4-K15',   studentCount:38 },
    { id:'cls_oto5',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 5-K15',   studentCount:36 },
    { id:'cls_oto6',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 6-K15',   studentCount:36 },
    { id:'cls_oto7',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 7-K15',   studentCount:36 },
    { id:'cls_oto8',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 8-K15',   studentCount:36 },
    { id:'cls_oto9',     majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 9-K15',   studentCount:35 },
    { id:'cls_oto10',    majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 10-K15',  studentCount:35 },
    { id:'cls_oto11',    majorId:'major_oto',  cohortId:'cohort_k15', code:'Ô TÔ 11-K15',  studentCount:34 },
    { id:'cls_cdt1',     majorId:'major_cdt',  cohortId:'cohort_k15', code:'CĐT1-K15',     studentCount:36 },
    { id:'cls_cdt2',     majorId:'major_cdt',  cohortId:'cohort_k15', code:'CĐT2-K15',     studentCount:36 },
    { id:'cls_cdt3',     majorId:'major_cdt',  cohortId:'cohort_k15', code:'CĐT3-K15',     studentCount:35 },
    { id:'cls_cdt4',     majorId:'major_cdt',  cohortId:'cohort_k15', code:'CĐT4-K15',     studentCount:35 },
    { id:'cls_dcn1',     majorId:'major_dcn',  cohortId:'cohort_k15', code:'ĐCN 1-K15',    studentCount:38 },
    { id:'cls_dcn2',     majorId:'major_dcn',  cohortId:'cohort_k15', code:'ĐCN 2-K15',    studentCount:38 },
    { id:'cls_dcn3',     majorId:'major_dcn',  cohortId:'cohort_k15', code:'ĐCN 3-K15',    studentCount:37 },
    { id:'cls_dcn4',     majorId:'major_dcn',  cohortId:'cohort_k15', code:'ĐCN 4-K15',    studentCount:37 },
    { id:'cls_tdh1',     majorId:'major_tdh',  cohortId:'cohort_k15', code:'TĐH 1-K15',    studentCount:36 },
    { id:'cls_tdh2',     majorId:'major_tdh',  cohortId:'cohort_k15', code:'TĐH 2-K15',    studentCount:36 },
    { id:'cls_tdh3',     majorId:'major_tdh',  cohortId:'cohort_k15', code:'TĐH 3-K15',    studentCount:35 },
    { id:'cls_dtcn1',    majorId:'major_dtcn', cohortId:'cohort_k15', code:'ĐTCN 1-K15',   studentCount:36 },
    { id:'cls_dtcn2',    majorId:'major_dtcn', cohortId:'cohort_k15', code:'ĐTCN 2-K15',   studentCount:36 },
    { id:'cls_dtcn_clc', majorId:'major_dtcn', cohortId:'cohort_k15', code:'ĐTCN CLC-K15', studentCount:28 },
    { id:'cls_cnctm',    majorId:'major_cnctm',cohortId:'cohort_k15', code:'CNCTM-K15',    studentCount:35 },
    { id:'cls_ktml1',    majorId:'major_ktml', cohortId:'cohort_k15', code:'KTML1-K15',    studentCount:35 },
    { id:'cls_ktml2',    majorId:'major_ktml', cohortId:'cohort_k15', code:'KTML2-K15',    studentCount:35 },
    { id:'cls_ddd',      majorId:'major_ddd',  cohortId:'cohort_k15', code:'ĐDD-K15',      studentCount:35 },
    { id:'cls_clc_dcn',  majorId:'major_dtcn', cohortId:'cohort_k15', code:'CLC-ĐCN K15',  studentCount:28 },
    { id:'cls_tmdt1',    majorId:'major_tmdt', cohortId:'cohort_k15', code:'TMĐT1-K15',    studentCount:36 },
    { id:'cls_tmdt2',    majorId:'major_tmdt', cohortId:'cohort_k15', code:'TMĐT2-K15',    studentCount:36 },
    { id:'cls_qtdn',     majorId:'major_qtdn', cohortId:'cohort_k15', code:'QTDN-K15',     studentCount:38 },
    { id:'cls_ktdn',     majorId:'major_ktdn', cohortId:'cohort_k15', code:'KTDN-K15',     studentCount:38 },
    { id:'cls_qtdn2',    majorId:'major_qtdn', cohortId:'cohort_k15', code:'QTDN2-K15',    studentCount:36 },
    { id:'cls_tdh1_k16', majorId:'major_tdh',  cohortId:'cohort_k16', code:'TĐH 1-K16',    studentCount:36 },
  ]});
  console.log('✓ classGroups (54)');

  // 7. SUBJECTS
  await prisma.subject.createMany({ data: [
    { id:'sub_ct',      code:'LMH01',   name:'Chính trị',                           credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_pl',      code:'LMH02',   name:'Pháp luật',                           credits:2, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_toan',    code:'LMH03',   name:'Toán cao cấp',                        credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_av1',     code:'LMH07',   name:'Anh văn 1',                           credits:4, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_av2',     code:'LMH08',   name:'Anh văn 2',                           credits:4, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_knm',     code:'LMH04',   name:'Kỹ năng mềm',                         credits:2, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_ctmt',    code:'LMH05',   name:'Cấu trúc máy tính',                   credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_gdtc',    code:'MH00007', name:'Giáo dục thể chất',                   credits:0, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_xdweb',   code:'LMH40',   name:'Xây dựng Website',                    credits:4, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_lmtcan',  code:'LMH11',   name:'Lập trình căn bản',                   credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_dhua',    code:'LMH09',   name:'Đồ họa ứng dụng',                     credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_nmmt',    code:'LMH13',   name:'Nhập môn mạng máy tính',              credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_sql',     code:'LMH24',   name:'HQT cơ sở dữ liệu SQL-Server',        credits:4, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_lphuong', code:'IT301',   name:'Lập trình hướng đối tượng',            credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_csdl',    code:'IT302',   name:'Cơ sở dữ liệu',                       credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_laptC',   code:'IT303',   name:'Lập trình C',                         credits:2, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_lapCsharp',code:'IT304',  name:'Lập trình C#',                        credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_lapPHP',  code:'IT305',   name:'Lập trình PHP',                       credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_pttkht',  code:'IT306',   name:'Phân tích thiết kế hệ thống',         credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_xdpm',    code:'IT307',   name:'Xây dựng phần mềm quản lý',           credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_ltdidong',code:'IT308',   name:'Lập trình thiết bị di động',           credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_lpservice',code:'IT309',  name:'Lập trình Service',                   credits:2, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_hdlinux', code:'IT310',   name:'Hệ điều hành Linux',                  credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_qtmangwin',code:'IT311',  name:'Quản trị mạng Windows',               credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_qtmanglin',code:'IT312',  name:'Quản trị mạng Linux',                 credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_anninh',  code:'IT313',   name:'An ninh mạng',                        credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_lpmangg', code:'IT314',   name:'Lập trình mạng',                      credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_cnkhong', code:'IT315',   name:'Công nghệ mạng không dây',            credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_tkxdmang',code:'IT316',   name:'Thiết kế xây dựng mạng LAN',          credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_baotrimt',code:'IT317',   name:'Bảo trì hệ thống máy tính',           credits:2, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_ctdlgt',  code:'IT318',   name:'Cấu trúc dữ liệu & giải thuật',       credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_cnpm',    code:'IT319',   name:'Công nghệ phần mềm',                  credits:3, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_qldacntt',code:'IT320',   name:'Quản lý dự án CNTT',                  credits:2, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_antoabm', code:'IT321',   name:'An toàn & bảo mật thông tin',         credits:2, roomType:'THEORY',   isPractice:false, requiresConsecutive:false },
    { id:'sub_xdwebpmm',code:'IT322',   name:'XD Website bằng PMMNM',               credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_qtwebfw', code:'IT323',   name:'Quản trị website với Framework',       credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_hinhhoaco',code:'TK301',  name:'Hình họa cơ bản',                     credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_tahinh2d',code:'TK302',   name:'Tạo hình 2D',                         credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_coreldraw',code:'TK303',  name:'Corel Draw',                          credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_pshop',   code:'TK304',   name:'Photoshop / Xử lý ảnh',               credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_dhoahn',  code:'TK305',   name:'Đồ họa hình động',                    credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_dh3d',    code:'TK306',   name:'Đồ họa 3D',                           credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_tkgdweb', code:'TK307',   name:'Thiết kế giao diện Website',           credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_tkbapbi', code:'TK308',   name:'TK nhãn mác bao bì sản phẩm',         credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_tkqbsp',  code:'TK309',   name:'TKĐH quảng bá sản phẩm',              credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_dungvideo',code:'TK310',  name:'Dựng Video',                          credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:true  },
    { id:'sub_tkdantrang',code:'TK311', name:'TK dàn trang ấn phẩm',                credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_tkthieuhi',code:'TK312',  name:'TK nhận diện thương hiệu',             credits:3, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
    { id:'sub_ktchanh', code:'TK313',   name:'Kỹ thuật chụp ảnh',                   credits:2, roomType:'PRACTICE', isPractice:true,  requiresConsecutive:false },
  ]});
  console.log('✓ subjects (49)');

  // 8. CURRICULA
  await prisma.curriculum.createMany({ data: [
    { id:'cur_ltmt_hk1_ct',     majorId:'major_ltmt', subjectId:'sub_ct',      semesterNo:1, weekStart:4,  weekEnd:20, periodsPerWeek:3 },
    { id:'cur_ltmt_hk1_pl',     majorId:'major_ltmt', subjectId:'sub_pl',      semesterNo:1, weekStart:4,  weekEnd:15, periodsPerWeek:2 },
    { id:'cur_ltmt_hk1_toan',   majorId:'major_ltmt', subjectId:'sub_toan',    semesterNo:1, weekStart:4,  weekEnd:20, periodsPerWeek:3 },
    { id:'cur_ltmt_hk1_av1',    majorId:'major_ltmt', subjectId:'sub_av1',     semesterNo:1, weekStart:4,  weekEnd:20, periodsPerWeek:3 },
    { id:'cur_ltmt_hk1_knm',    majorId:'major_ltmt', subjectId:'sub_knm',     semesterNo:1, weekStart:4,  weekEnd:15, periodsPerWeek:2 },
    { id:'cur_ltmt_hk1_ctmt',   majorId:'major_ltmt', subjectId:'sub_ctmt',    semesterNo:1, weekStart:4,  weekEnd:15, periodsPerWeek:3 },
    { id:'cur_ltmt_hk2_av2',    majorId:'major_ltmt', subjectId:'sub_av2',     semesterNo:2, weekStart:21, weekEnd:37, periodsPerWeek:3 },
    { id:'cur_ltmt_hk2_lmtcan', majorId:'major_ltmt', subjectId:'sub_lmtcan',  semesterNo:2, weekStart:21, weekEnd:37, periodsPerWeek:4 },
    { id:'cur_ltmt_hk2_xdweb',  majorId:'major_ltmt', subjectId:'sub_xdweb',   semesterNo:2, weekStart:24, weekEnd:37, periodsPerWeek:3 },
    { id:'cur_ltmt_hk2_sql',    majorId:'major_ltmt', subjectId:'sub_sql',     semesterNo:2, weekStart:23, weekEnd:37, periodsPerWeek:4 },
    { id:'cur_ltmt_hk2_dhua',   majorId:'major_ltmt', subjectId:'sub_dhua',    semesterNo:2, weekStart:21, weekEnd:33, periodsPerWeek:3 },
    { id:'cur_ltmt_hk3_lph',    majorId:'major_ltmt', subjectId:'sub_lphuong', semesterNo:3, weekStart:1,  weekEnd:15, periodsPerWeek:3 },
    { id:'cur_ltmt_hk3_csdl',   majorId:'major_ltmt', subjectId:'sub_csdl',    semesterNo:3, weekStart:1,  weekEnd:10, periodsPerWeek:4 },
    { id:'cur_ltmt_hk3_ctdl',   majorId:'major_ltmt', subjectId:'sub_ctdlgt',  semesterNo:3, weekStart:1,  weekEnd:15, periodsPerWeek:3 },
    { id:'cur_ltmt_hk4_csharp', majorId:'major_ltmt', subjectId:'sub_lapCsharp',semesterNo:4,weekStart:23, weekEnd:32, periodsPerWeek:3 },
    { id:'cur_ltmt_hk4_pttkht', majorId:'major_ltmt', subjectId:'sub_pttkht',  semesterNo:4, weekStart:23, weekEnd:32, periodsPerWeek:3 },
    { id:'cur_ltmt_hk4_btmt',   majorId:'major_ltmt', subjectId:'sub_baotrimt',semesterNo:4, weekStart:23, weekEnd:32, periodsPerWeek:2 },
    { id:'cur_ltmt_hk4_av2_2',  majorId:'major_ltmt', subjectId:'sub_av2',     semesterNo:4, weekStart:23, weekEnd:32, periodsPerWeek:3 },
    { id:'cur_ltmt_hk5_xdpm',   majorId:'major_ltmt', subjectId:'sub_xdpm',    semesterNo:5, weekStart:16, weekEnd:25, periodsPerWeek:3 },
    { id:'cur_ltmt_hk5_hdlinux',majorId:'major_ltmt', subjectId:'sub_hdlinux', semesterNo:5, weekStart:16, weekEnd:25, periodsPerWeek:3 },
    { id:'cur_ltmt_hk5_ltdidong',majorId:'major_ltmt',subjectId:'sub_ltdidong',semesterNo:5, weekStart:16, weekEnd:25, periodsPerWeek:3 },
    { id:'cur_ltmt_hk5_lpservice',majorId:'major_ltmt',subjectId:'sub_lpservice',semesterNo:5,weekStart:17,weekEnd:26,periodsPerWeek:2 },
    { id:'cur_qtm_hk5_lpmangg', majorId:'major_qtm',  subjectId:'sub_lpmangg', semesterNo:5, weekStart:17, weekEnd:26, periodsPerWeek:3 },
    { id:'cur_qtm_hk5_anninh',  majorId:'major_qtm',  subjectId:'sub_anninh',  semesterNo:5, weekStart:17, weekEnd:26, periodsPerWeek:3 },
    { id:'cur_qtm_hk4_tkxdmang',majorId:'major_qtm',  subjectId:'sub_tkxdmang',semesterNo:4, weekStart:24, weekEnd:33, periodsPerWeek:3 },
    { id:'cur_qtm_hk4_baotrimt',majorId:'major_qtm',  subjectId:'sub_baotrimt',semesterNo:4, weekStart:23, weekEnd:32, periodsPerWeek:2 },
    { id:'cur_qtm_hk4_csharp',  majorId:'major_qtm',  subjectId:'sub_lapCsharp',semesterNo:4,weekStart:23, weekEnd:32, periodsPerWeek:3 },
    { id:'cur_udpm_hk5_xdpm',   majorId:'major_udpm', subjectId:'sub_xdpm',    semesterNo:5, weekStart:16, weekEnd:25, periodsPerWeek:3 },
    { id:'cur_udpm_hk5_cnpm',   majorId:'major_udpm', subjectId:'sub_cnpm',    semesterNo:5, weekStart:16, weekEnd:26, periodsPerWeek:3 },
    { id:'cur_udpm_hk5_qldacntt',majorId:'major_udpm',subjectId:'sub_qldacntt',semesterNo:5, weekStart:16, weekEnd:26, periodsPerWeek:2 },
    { id:'cur_udpm_hk5_atbm',   majorId:'major_udpm', subjectId:'sub_antoabm', semesterNo:5, weekStart:16, weekEnd:25, periodsPerWeek:2 },
    { id:'cur_udpm_hk5_hdlinux',majorId:'major_udpm', subjectId:'sub_hdlinux', semesterNo:5, weekStart:16, weekEnd:25, periodsPerWeek:3 },
    { id:'cur_tkdh_hk1_ct',     majorId:'major_tkdh', subjectId:'sub_ct',      semesterNo:1, weekStart:4,  weekEnd:15, periodsPerWeek:3 },
    { id:'cur_tkdh_hk1_knm',    majorId:'major_tkdh', subjectId:'sub_knm',     semesterNo:1, weekStart:4,  weekEnd:15, periodsPerWeek:2 },
    { id:'cur_tkdh_hk1_hinhhoaco',majorId:'major_tkdh',subjectId:'sub_hinhhoaco',semesterNo:1,weekStart:4, weekEnd:15, periodsPerWeek:3 },
    { id:'cur_tkdh_hk3_tahinh2d',majorId:'major_tkdh',subjectId:'sub_tahinh2d',semesterNo:3, weekStart:1,  weekEnd:15, periodsPerWeek:3 },
    { id:'cur_tkdh_hk3_coreldraw',majorId:'major_tkdh',subjectId:'sub_coreldraw',semesterNo:3,weekStart:1, weekEnd:15, periodsPerWeek:3 },
    { id:'cur_tkdh_hk5_dhoahn', majorId:'major_tkdh', subjectId:'sub_dhoahn',  semesterNo:5, weekStart:16, weekEnd:20, periodsPerWeek:3 },
    { id:'cur_tkdh_hk5_tkgdweb',majorId:'major_tkdh', subjectId:'sub_tkgdweb', semesterNo:5, weekStart:16, weekEnd:25, periodsPerWeek:3 },
    { id:'cur_tkdh_hk5_tkbapbi',majorId:'major_tkdh', subjectId:'sub_tkbapbi', semesterNo:5, weekStart:18, weekEnd:27, periodsPerWeek:3 },
    { id:'cur_tkdh_hk5_tkqbsp', majorId:'major_tkdh', subjectId:'sub_tkqbsp',  semesterNo:5, weekStart:16, weekEnd:20, periodsPerWeek:3 },
    { id:'cur_tkdh_hk5_dungvideo',majorId:'major_tkdh',subjectId:'sub_dungvideo',semesterNo:5,weekStart:16,weekEnd:25, periodsPerWeek:3 },
  ]});
  console.log('✓ curricula (42)');

  // 9. ASSIGNMENTS
  await prisma.assignment.createMany({ data: [
    { id:'asn_xdpm_ltmt1',    teacherId:'gv_cuong',      classGroupId:'cls_ltmt1' },
    { id:'asn_xdpm_ltmt2',    teacherId:'gv_binh_cuong', classGroupId:'cls_ltmt2' },
    { id:'asn_xdpm_ltmt3',    teacherId:'gv_binh_cuong', classGroupId:'cls_ltmt3' },
    { id:'asn_xdpm_ltmt4',    teacherId:'gv_binh_cuong', classGroupId:'cls_ltmt4' },
    { id:'asn_linux_ltmt1',   teacherId:'gv_han',        classGroupId:'cls_ltmt1' },
    { id:'asn_linux_ltmt2',   teacherId:'gv_han',        classGroupId:'cls_ltmt2' },
    { id:'asn_linux_ltmt3',   teacherId:'gv_han',        classGroupId:'cls_ltmt3' },
    { id:'asn_linux_ltmt4',   teacherId:'gv_han',        classGroupId:'cls_ltmt4' },
    { id:'asn_ltdidong_ltmt1',teacherId:'gv_tung_ct',    classGroupId:'cls_ltmt1' },
    { id:'asn_ltdidong_ltmt2',teacherId:'gv_tung_ct',    classGroupId:'cls_ltmt2' },
    { id:'asn_ltdidong_ltmt3',teacherId:'gv_tung_ct',    classGroupId:'cls_ltmt3' },
    { id:'asn_ltdidong_ltmt4',teacherId:'gv_tung_ct',    classGroupId:'cls_ltmt4' },
    { id:'asn_lpsvc_ltmt5',   teacherId:'gv_muoi',       classGroupId:'cls_ltmt5' },
    { id:'asn_lpsvc_ltmt6',   teacherId:'gv_muoi',       classGroupId:'cls_ltmt6' },
    { id:'asn_lpsvc_ltmt56',  teacherId:'gv_cuong',      classGroupId:'cls_ltmt5' },
    { id:'asn_lpmang_qtm1',   teacherId:'gv_muoi',       classGroupId:'cls_qtm1' },
    { id:'asn_anninh_qtm1',   teacherId:'gv_quoc_tuan',  classGroupId:'cls_qtm1' },
    { id:'asn_csharp_ltmt1',  teacherId:'gv_ho_tung',    classGroupId:'cls_ltmt1' },
    { id:'asn_csharp_ltmt2',  teacherId:'gv_ho_tung',    classGroupId:'cls_ltmt2' },
    { id:'asn_csharp_ltmt3',  teacherId:'gv_cuong',      classGroupId:'cls_ltmt3' },
    { id:'asn_csharp_ltmt4',  teacherId:'gv_cuong',      classGroupId:'cls_ltmt4' },
    { id:'asn_pttkht_ltmt1',  teacherId:'gv_uy',         classGroupId:'cls_ltmt1' },
    { id:'asn_pttkht_ltmt2',  teacherId:'gv_uy',         classGroupId:'cls_ltmt2' },
    { id:'asn_pttkht_ltmt3',  teacherId:'gv_hoa',        classGroupId:'cls_ltmt3' },
    { id:'asn_pttkht_ltmt4',  teacherId:'gv_hoa',        classGroupId:'cls_ltmt4' },
    { id:'asn_baotrimt_ltmt1',teacherId:'gv_quoc',       classGroupId:'cls_ltmt1' },
    { id:'asn_baotrimt_ltmt2',teacherId:'gv_quoc',       classGroupId:'cls_ltmt2' },
    { id:'asn_tkxdmang_qtm',  teacherId:'gv_toan',       classGroupId:'cls_qtm1' },
    { id:'asn_btmt_qtm',      teacherId:'gv_quoc',       classGroupId:'cls_qtm1' },
    { id:'asn_xdpm_udpm1',    teacherId:'gv_cuong',      classGroupId:'cls_udpm1' },
    { id:'asn_cnpm_udpm1',    teacherId:'gv_hoa',        classGroupId:'cls_udpm1' },
    { id:'asn_qldacntt_udpm', teacherId:'gv_hoa',        classGroupId:'cls_udpm1' },
    { id:'asn_atbm_udpm1',    teacherId:'gv_quoc_tuan',  classGroupId:'cls_udpm1' },
    { id:'asn_linux_udpm1',   teacherId:'gv_tung_ng',    classGroupId:'cls_udpm1' },
    { id:'asn_dhoahn_tkdh1',  teacherId:'gv_anh_tkdh',   classGroupId:'cls_tkdh1' },
    { id:'asn_dhoahn_tkdh2',  teacherId:'gv_anh_tkdh',   classGroupId:'cls_tkdh2' },
    { id:'asn_dhoahn_tkdh3',  teacherId:'gv_anh_tkdh',   classGroupId:'cls_tkdh3' },
    { id:'asn_dhoahn_tkdh4',  teacherId:'gv_anh_tkdh',   classGroupId:'cls_tkdh4' },
    { id:'asn_tkgdweb_tkdh5', teacherId:'gv_cuong',      classGroupId:'cls_tkdh5' },
    { id:'asn_tkgdweb_tkdh6', teacherId:'gv_cuong',      classGroupId:'cls_tkdh6' },
    { id:'asn_tkbb_tkdh5',    teacherId:'gv_quang_tkdh', classGroupId:'cls_tkdh5' },
    { id:'asn_tkbb_tkdh6',    teacherId:'gv_quang_tkdh', classGroupId:'cls_tkdh6' },
    { id:'asn_tkqb_tkdh1',    teacherId:'gv_thanh_tkdh', classGroupId:'cls_tkdh1' },
    { id:'asn_tkqb_tkdh2',    teacherId:'gv_thanh_tkdh', classGroupId:'cls_tkdh2' },
    { id:'asn_tkqb_tkdh3',    teacherId:'gv_trang',      classGroupId:'cls_tkdh3' },
    { id:'asn_tkqb_tkdh4',    teacherId:'gv_trang',      classGroupId:'cls_tkdh4' },
    { id:'asn_video_tkdh1',   teacherId:'gv_nhung',      classGroupId:'cls_tkdh1' },
    { id:'asn_video_tkdh2',   teacherId:'gv_nhung',      classGroupId:'cls_tkdh2' },
    { id:'asn_video_tkdh3',   teacherId:'gv_nhung',      classGroupId:'cls_tkdh3' },
    { id:'asn_video_tkdh5',   teacherId:'gv_loi_tkdh',   classGroupId:'cls_tkdh5' },
    { id:'asn_ct_ltmt1',      teacherId:'gv_lan_ct',     classGroupId:'cls_ltmt1' },
    { id:'asn_ct_ltmt2',      teacherId:'gv_lan_ct',     classGroupId:'cls_ltmt2' },
    { id:'asn_ct_ltmt3',      teacherId:'gv_lan_ct',     classGroupId:'cls_ltmt3' },
    { id:'asn_ct_ltmt4',      teacherId:'gv_lan_ct',     classGroupId:'cls_ltmt4' },
    { id:'asn_ct_tkdh1',      teacherId:'gv_ngoc',       classGroupId:'cls_tkdh1' },
    { id:'asn_ct_tkdh2',      teacherId:'gv_ngoc',       classGroupId:'cls_tkdh2' },
    { id:'asn_toan_ltmt1',    teacherId:'gv_dung_toan',  classGroupId:'cls_ltmt1' },
    { id:'asn_toan_ltmt2',    teacherId:'gv_dung_toan',  classGroupId:'cls_ltmt2' },
    { id:'asn_toan_tkdh1',    teacherId:'gv_sam',        classGroupId:'cls_tkdh1' },
    { id:'asn_av1_ltmt1',     teacherId:'gv_quynh_anh',  classGroupId:'cls_ltmt1' },
    { id:'asn_av1_ltmt2',     teacherId:'gv_huyen',      classGroupId:'cls_ltmt2' },
    { id:'asn_av1_ltmt3',     teacherId:'gv_ninh_ha',    classGroupId:'cls_ltmt3' },
    { id:'asn_av1_ltmt4',     teacherId:'gv_ninh_ha',    classGroupId:'cls_ltmt4' },
    { id:'asn_av1_tkdh1',     teacherId:'gv_huyen',      classGroupId:'cls_tkdh1' },
    { id:'asn_av1_tkdh2',     teacherId:'gv_ninh_ha',    classGroupId:'cls_tkdh2' },
  ]});
  console.log('✓ assignments (64)');

  // 10. TEACHING UNITS
  await prisma.teachingUnit.createMany({ data: [
    { id:'tu_xdpm_ltmt1',    subjectId:'sub_xdpm',    assignmentId:'asn_xdpm_ltmt1',    type:'THEORY',   name:'XDPM-LTMT1-K15-HK5' },
    { id:'tu_xdpm_ltmt2',    subjectId:'sub_xdpm',    assignmentId:'asn_xdpm_ltmt2',    type:'THEORY',   name:'XDPM-LTMT2-K15-HK5' },
    { id:'tu_xdpm_ltmt3',    subjectId:'sub_xdpm',    assignmentId:'asn_xdpm_ltmt3',    type:'THEORY',   name:'XDPM-LTMT3-K15-HK5' },
    { id:'tu_xdpm_ltmt4',    subjectId:'sub_xdpm',    assignmentId:'asn_xdpm_ltmt4',    type:'THEORY',   name:'XDPM-LTMT4-K15-HK5' },
    { id:'tu_linux_ltmt1',   subjectId:'sub_hdlinux', assignmentId:'asn_linux_ltmt1',   type:'PRACTICE', name:'HĐH-Linux-LTMT1-K15-HK5' },
    { id:'tu_linux_ltmt2',   subjectId:'sub_hdlinux', assignmentId:'asn_linux_ltmt2',   type:'PRACTICE', name:'HĐH-Linux-LTMT2-K15-HK5' },
    { id:'tu_linux_ltmt3',   subjectId:'sub_hdlinux', assignmentId:'asn_linux_ltmt3',   type:'PRACTICE', name:'HĐH-Linux-LTMT3-K15-HK5' },
    { id:'tu_linux_ltmt4',   subjectId:'sub_hdlinux', assignmentId:'asn_linux_ltmt4',   type:'PRACTICE', name:'HĐH-Linux-LTMT4-K15-HK5' },
    { id:'tu_ltdidong_ltmt1',subjectId:'sub_ltdidong',assignmentId:'asn_ltdidong_ltmt1',type:'PRACTICE', name:'LTDĐ-LTMT1-K15-HK5', conflictGroupId:'cg_ltdidong_hk5' },
    { id:'tu_ltdidong_ltmt2',subjectId:'sub_ltdidong',assignmentId:'asn_ltdidong_ltmt2',type:'PRACTICE', name:'LTDĐ-LTMT2-K15-HK5', conflictGroupId:'cg_ltdidong_hk5' },
    { id:'tu_ltdidong_ltmt3',subjectId:'sub_ltdidong',assignmentId:'asn_ltdidong_ltmt3',type:'PRACTICE', name:'LTDĐ-LTMT3-K15-HK5', conflictGroupId:'cg_ltdidong_hk5' },
    { id:'tu_ltdidong_ltmt4',subjectId:'sub_ltdidong',assignmentId:'asn_ltdidong_ltmt4',type:'PRACTICE', name:'LTDĐ-LTMT4-K15-HK5', conflictGroupId:'cg_ltdidong_hk5' },
    { id:'tu_lpsvc_ltmt5',   subjectId:'sub_lpservice',assignmentId:'asn_lpsvc_ltmt5', type:'PRACTICE', name:'LP-Service-LTMT5-K15-HK5' },
    { id:'tu_lpsvc_ltmt6',   subjectId:'sub_lpservice',assignmentId:'asn_lpsvc_ltmt6', type:'PRACTICE', name:'LP-Service-LTMT6-K15-HK5' },
    { id:'tu_lpmang_qtm1',   subjectId:'sub_lpmangg', assignmentId:'asn_lpmang_qtm1',  type:'PRACTICE', name:'LP-Mạng-QTM1-K15-HK5' },
    { id:'tu_anninh_qtm1',   subjectId:'sub_anninh',  assignmentId:'asn_anninh_qtm1',  type:'THEORY',   name:'AnNinh-QTM1-K15-HK5' },
    { id:'tu_csharp_ltmt1',  subjectId:'sub_lapCsharp',assignmentId:'asn_csharp_ltmt1',type:'PRACTICE', name:'C#-LTMT1-K15-HK4' },
    { id:'tu_csharp_ltmt2',  subjectId:'sub_lapCsharp',assignmentId:'asn_csharp_ltmt2',type:'PRACTICE', name:'C#-LTMT2-K15-HK4' },
    { id:'tu_csharp_ltmt3',  subjectId:'sub_lapCsharp',assignmentId:'asn_csharp_ltmt3',type:'PRACTICE', name:'C#-LTMT3-K15-HK4' },
    { id:'tu_csharp_ltmt4',  subjectId:'sub_lapCsharp',assignmentId:'asn_csharp_ltmt4',type:'PRACTICE', name:'C#-LTMT4-K15-HK4' },
    { id:'tu_pttkht_ltmt1',  subjectId:'sub_pttkht',  assignmentId:'asn_pttkht_ltmt1', type:'THEORY',   name:'PTTKHT-LTMT1-K15-HK4' },
    { id:'tu_pttkht_ltmt2',  subjectId:'sub_pttkht',  assignmentId:'asn_pttkht_ltmt2', type:'THEORY',   name:'PTTKHT-LTMT2-K15-HK4' },
    { id:'tu_pttkht_ltmt3',  subjectId:'sub_pttkht',  assignmentId:'asn_pttkht_ltmt3', type:'THEORY',   name:'PTTKHT-LTMT3-K15-HK4' },
    { id:'tu_pttkht_ltmt4',  subjectId:'sub_pttkht',  assignmentId:'asn_pttkht_ltmt4', type:'THEORY',   name:'PTTKHT-LTMT4-K15-HK4' },
    { id:'tu_xdpm_udpm1',    subjectId:'sub_xdpm',    assignmentId:'asn_xdpm_udpm1',   type:'THEORY',   name:'XDPM-UDPM1-K15-HK5' },
    { id:'tu_cnpm_udpm1',    subjectId:'sub_cnpm',    assignmentId:'asn_cnpm_udpm1',   type:'THEORY',   name:'CNPM-UDPM1-K15-HK5' },
    { id:'tu_linux_udpm1',   subjectId:'sub_hdlinux', assignmentId:'asn_linux_udpm1',  type:'PRACTICE', name:'HĐH-Linux-UDPM1-K15-HK5' },
    { id:'tu_dhoahn_tkdh1',  subjectId:'sub_dhoahn',  assignmentId:'asn_dhoahn_tkdh1', type:'PRACTICE', name:'ĐH-HĐ-TKĐH1-K15-HK5', conflictGroupId:'cg_dhoahn_hk5' },
    { id:'tu_dhoahn_tkdh2',  subjectId:'sub_dhoahn',  assignmentId:'asn_dhoahn_tkdh2', type:'PRACTICE', name:'ĐH-HĐ-TKĐH2-K15-HK5', conflictGroupId:'cg_dhoahn_hk5' },
    { id:'tu_dhoahn_tkdh3',  subjectId:'sub_dhoahn',  assignmentId:'asn_dhoahn_tkdh3', type:'PRACTICE', name:'ĐH-HĐ-TKĐH3-K15-HK5', conflictGroupId:'cg_dhoahn_hk5' },
    { id:'tu_dhoahn_tkdh4',  subjectId:'sub_dhoahn',  assignmentId:'asn_dhoahn_tkdh4', type:'PRACTICE', name:'ĐH-HĐ-TKĐH4-K15-HK5', conflictGroupId:'cg_dhoahn_hk5' },
    { id:'tu_tkgdweb_tkdh5', subjectId:'sub_tkgdweb', assignmentId:'asn_tkgdweb_tkdh5',type:'PRACTICE', name:'TKGDW-TKĐH5-K15-HK5' },
    { id:'tu_tkgdweb_tkdh6', subjectId:'sub_tkgdweb', assignmentId:'asn_tkgdweb_tkdh6',type:'PRACTICE', name:'TKGDW-TKĐH6-K15-HK5' },
    { id:'tu_ct_ltmt1',      subjectId:'sub_ct',      assignmentId:'asn_ct_ltmt1',     type:'THEORY',   name:'CT-LTMT1-K15-HK1' },
    { id:'tu_ct_ltmt2',      subjectId:'sub_ct',      assignmentId:'asn_ct_ltmt2',     type:'THEORY',   name:'CT-LTMT2-K15-HK1' },
    { id:'tu_ct_tkdh1',      subjectId:'sub_ct',      assignmentId:'asn_ct_tkdh1',     type:'THEORY',   name:'CT-TKĐH1-K15-HK1' },
    { id:'tu_toan_ltmt1',    subjectId:'sub_toan',    assignmentId:'asn_toan_ltmt1',   type:'THEORY',   name:'TCCap-LTMT1-K15-HK1' },
    { id:'tu_toan_ltmt2',    subjectId:'sub_toan',    assignmentId:'asn_toan_ltmt2',   type:'THEORY',   name:'TCCap-LTMT2-K15-HK1' },
    { id:'tu_av1_ltmt1',     subjectId:'sub_av1',     assignmentId:'asn_av1_ltmt1',    type:'PRACTICE', name:'AV1-LTMT1-K15-HK1' },
    { id:'tu_av1_ltmt2',     subjectId:'sub_av1',     assignmentId:'asn_av1_ltmt2',    type:'PRACTICE', name:'AV1-LTMT2-K15-HK1' },
    { id:'tu_av1_ltmt3',     subjectId:'sub_av1',     assignmentId:'asn_av1_ltmt3',    type:'PRACTICE', name:'AV1-LTMT3-K15-HK1' },
    { id:'tu_av1_tkdh1',     subjectId:'sub_av1',     assignmentId:'asn_av1_tkdh1',    type:'PRACTICE', name:'AV1-TKĐH1-K15-HK1' },
  ]});
  console.log('✓ teachingUnits (42)');

  // 11. SCHEDULES
  await prisma.schedule.createMany({ data: [
    { id:'sch_toan_ltmt1_t2_w4',     teachingUnitId:'tu_toan_ltmt1',    roomId:'room_a17_405', dayOfWeek:2, periodStart:4, periodEnd:6, weekNumber:4,  mode:'OFFLINE' },
    { id:'sch_toan_ltmt1_t2_w5',     teachingUnitId:'tu_toan_ltmt1',    roomId:'room_a17_405', dayOfWeek:2, periodStart:4, periodEnd:6, weekNumber:5,  mode:'OFFLINE' },
    { id:'sch_toan_ltmt1_t2_w6',     teachingUnitId:'tu_toan_ltmt1',    roomId:'room_a17_405', dayOfWeek:2, periodStart:4, periodEnd:6, weekNumber:6,  mode:'OFFLINE' },
    { id:'sch_ct_ltmt1_t3_w4',       teachingUnitId:'tu_ct_ltmt1',      roomId:'room_a17_405', dayOfWeek:3, periodStart:4, periodEnd:6, weekNumber:4,  mode:'OFFLINE' },
    { id:'sch_ct_ltmt1_t3_w5',       teachingUnitId:'tu_ct_ltmt1',      roomId:'room_a17_405', dayOfWeek:3, periodStart:4, periodEnd:6, weekNumber:5,  mode:'OFFLINE' },
    { id:'sch_av1_ltmt1_t6_w4',      teachingUnitId:'tu_av1_ltmt1',     roomId:'room_pm_402',  dayOfWeek:6, periodStart:4, periodEnd:6, weekNumber:4,  mode:'OFFLINE' },
    { id:'sch_av1_ltmt1_t6_w5',      teachingUnitId:'tu_av1_ltmt1',     roomId:'room_pm_402',  dayOfWeek:6, periodStart:4, periodEnd:6, weekNumber:5,  mode:'OFFLINE' },
    { id:'sch_av1_ltmt1_t6_w6',      teachingUnitId:'tu_av1_ltmt1',     roomId:'room_pm_402',  dayOfWeek:6, periodStart:4, periodEnd:6, weekNumber:6,  mode:'OFFLINE' },
    { id:'sch_xdpm_ltmt1_t7_w16',    teachingUnitId:'tu_xdpm_ltmt1',    roomId:'room_a17_408', dayOfWeek:7, periodStart:4, periodEnd:6, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_xdpm_ltmt1_t7_w17',    teachingUnitId:'tu_xdpm_ltmt1',    roomId:'room_a17_408', dayOfWeek:7, periodStart:4, periodEnd:6, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_xdpm_ltmt1_t7_w18',    teachingUnitId:'tu_xdpm_ltmt1',    roomId:'room_a17_408', dayOfWeek:7, periodStart:4, periodEnd:6, weekNumber:18, mode:'OFFLINE' },
    { id:'sch_linux_ltmt1_t7_w16',   teachingUnitId:'tu_linux_ltmt1',   roomId:'room_a17_406', dayOfWeek:6, periodStart:4, periodEnd:6, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_linux_ltmt1_t7_w17',   teachingUnitId:'tu_linux_ltmt1',   roomId:'room_a17_406', dayOfWeek:6, periodStart:4, periodEnd:6, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_ltdidong_ltmt1_t7_w16',teachingUnitId:'tu_ltdidong_ltmt1',roomId:'room_a17_402', dayOfWeek:7, periodStart:1, periodEnd:3, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_ltdidong_ltmt2_t7_w16',teachingUnitId:'tu_ltdidong_ltmt2',roomId:'room_a17_405', dayOfWeek:7, periodStart:1, periodEnd:3, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_lpmang_qtm1_t5_w17',   teachingUnitId:'tu_lpmang_qtm1',   roomId:'room_a17_408', dayOfWeek:5, periodStart:4, periodEnd:6, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_lpmang_qtm1_t5_w18',   teachingUnitId:'tu_lpmang_qtm1',   roomId:'room_a17_408', dayOfWeek:5, periodStart:4, periodEnd:6, weekNumber:18, mode:'OFFLINE' },
    { id:'sch_anninh_qtm1_t5_w17',   teachingUnitId:'tu_anninh_qtm1',   roomId:'room_a17_408', dayOfWeek:5, periodStart:7, periodEnd:9, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_anninh_qtm1_t5_w18',   teachingUnitId:'tu_anninh_qtm1',   roomId:'room_a17_408', dayOfWeek:5, periodStart:7, periodEnd:9, weekNumber:18, mode:'OFFLINE' },
    { id:'sch_csharp_ltmt1_t5_w23',  teachingUnitId:'tu_csharp_ltmt1',  roomId:'room_pm_302',  dayOfWeek:5, periodStart:4, periodEnd:6, weekNumber:23, mode:'OFFLINE' },
    { id:'sch_csharp_ltmt1_t5_w24',  teachingUnitId:'tu_csharp_ltmt1',  roomId:'room_pm_302',  dayOfWeek:5, periodStart:4, periodEnd:6, weekNumber:24, mode:'OFFLINE' },
    { id:'sch_csharp_ltmt1_t5_w25',  teachingUnitId:'tu_csharp_ltmt1',  roomId:'room_pm_302',  dayOfWeek:5, periodStart:4, periodEnd:6, weekNumber:25, mode:'OFFLINE' },
    { id:'sch_pttkht_ltmt1_t4_w23',  teachingUnitId:'tu_pttkht_ltmt1',  roomId:'room_pm_302',  dayOfWeek:4, periodStart:4, periodEnd:6, weekNumber:23, mode:'OFFLINE' },
    { id:'sch_pttkht_ltmt1_t4_w24',  teachingUnitId:'tu_pttkht_ltmt1',  roomId:'room_pm_302',  dayOfWeek:4, periodStart:4, periodEnd:6, weekNumber:24, mode:'OFFLINE' },
    { id:'sch_csharp_ltmt2_t5_w23',  teachingUnitId:'tu_csharp_ltmt2',  roomId:'room_pm_306',  dayOfWeek:5, periodStart:4, periodEnd:6, weekNumber:23, mode:'OFFLINE' },
    { id:'sch_csharp_ltmt2_t5_w24',  teachingUnitId:'tu_csharp_ltmt2',  roomId:'room_pm_306',  dayOfWeek:5, periodStart:4, periodEnd:6, weekNumber:24, mode:'OFFLINE' },
    { id:'sch_linux_udpm1_t3_w16',   teachingUnitId:'tu_linux_udpm1',   roomId:'room_a17_502', dayOfWeek:3, periodStart:7, periodEnd:9, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_linux_udpm1_t3_w17',   teachingUnitId:'tu_linux_udpm1',   roomId:'room_a17_502', dayOfWeek:3, periodStart:7, periodEnd:9, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_cnpm_udpm1_t6_w16',    teachingUnitId:'tu_cnpm_udpm1',    roomId:'room_a17_403', dayOfWeek:6, periodStart:7, periodEnd:9, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_cnpm_udpm1_t6_w17',    teachingUnitId:'tu_cnpm_udpm1',    roomId:'room_a17_403', dayOfWeek:6, periodStart:7, periodEnd:9, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_dhoahn_tkdh1_t3_w16',  teachingUnitId:'tu_dhoahn_tkdh1',  roomId:'room_pm_404',  dayOfWeek:2, periodStart:1, periodEnd:3, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_dhoahn_tkdh1_t3_w17',  teachingUnitId:'tu_dhoahn_tkdh1',  roomId:'room_pm_404',  dayOfWeek:2, periodStart:1, periodEnd:3, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_dhoahn_tkdh2_t3_w16',  teachingUnitId:'tu_dhoahn_tkdh2',  roomId:'room_pm_404',  dayOfWeek:3, periodStart:1, periodEnd:3, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_tkgdweb_tkdh5_t2_w16', teachingUnitId:'tu_tkgdweb_tkdh5', roomId:'room_pm_304',  dayOfWeek:2, periodStart:4, periodEnd:6, weekNumber:16, mode:'OFFLINE' },
    { id:'sch_tkgdweb_tkdh5_t2_w17', teachingUnitId:'tu_tkgdweb_tkdh5', roomId:'room_pm_304',  dayOfWeek:2, periodStart:4, periodEnd:6, weekNumber:17, mode:'OFFLINE' },
    { id:'sch_tkgdweb_tkdh6_t3_w16', teachingUnitId:'tu_tkgdweb_tkdh6', roomId:'room_pm_304',  dayOfWeek:3, periodStart:4, periodEnd:6, weekNumber:16, mode:'OFFLINE' },
  ]});
  console.log('✓ schedules (36)');

  // 12. USERS
  await prisma.user.createMany({ data: [
    { id:'usr_admin1', email:'admin@school.edu.vn',             passwordHash:'$2a$12$59SXlB1GQPFYZ7RLKKMkMuSWPxDctAACj6rb2.bW9ZIpkEQOZpiaK', role:'ADMIN',   refId:null },
    { id:'usr_admin2', email:'phongdaotao@school.edu.vn',       passwordHash:'$2a$12$dF0lt0raVeQze0c23.1F9.5qfLYcTqrVZTYwRo6ZtHTDR84UucH6O', role:'ADMIN',   refId:null },
    { id:'usr_gv_cuong',  email:'cuong@school.edu.vn',          passwordHash:'$2a$12$aynORzkyYa7x7hsiQVZS9OhU6x/A.w/.48QJ039jxVlWTELFkKTpq', role:'TEACHER', refId:'gv_cuong' },
    { id:'usr_gv_han',    email:'han@school.edu.vn',            passwordHash:'$2a$12$A40dJnU3TxdAyrUoftKRze4M345hJpjUu2jKl8OeUNroSztmkxLO6', role:'TEACHER', refId:'gv_han' },
    { id:'usr_gv_muoi',   email:'muoiphuong@school.edu.vn',     passwordHash:'$2a$12$PcP3S9FWvw9n.pxVr9yscej/4l76QdfV4N9rzR3vw1KKNisX3QhRa', role:'TEACHER', refId:'gv_muoi' },
    { id:'usr_gv_toan',   email:'toan@school.edu.vn',           passwordHash:'$2a$12$XELJnzswfcsOgpVqsppCX.0UJxejYnTR6VQHVEb9n8ceg6K02GLJy', role:'TEACHER', refId:'gv_toan' },
    { id:'usr_gv_hoa',    email:'hoa@school.edu.vn',            passwordHash:'$2a$12$uSyG0dqKrCJeQNp1DxgOU.QsRR9gb3vLHmGuMv1Eovoqci5UlBxTO', role:'TEACHER', refId:'gv_hoa' },
    { id:'usr_gv_uy',     email:'uy@school.edu.vn',             passwordHash:'$2a$12$Sml5GL8XsOsQhPybVc8xeOtubF8BQkPAMyjlU7KQW.CNO0GyDmgpm',  role:'TEACHER', refId:'gv_uy' },
    { id:'usr_sv_ltmt1',  email:'sv.ltmt1@student.school.edu.vn', passwordHash:'$2a$12$f6xKsDpeYFS2VcD9VnswpeF8CvzRtU0HTRH5v6Os1l4lpEh4La43O', role:'STUDENT', refId:'cls_ltmt1' },
    { id:'usr_sv_ltmt2',  email:'sv.ltmt2@student.school.edu.vn', passwordHash:'$2a$12$mX6/bo04uQsE5aIn4IeIpOJTHy2mBQLcajWJb8wYiduc6NTewn/36', role:'STUDENT', refId:'cls_ltmt2' },
    { id:'usr_sv_qtm1',   email:'sv.qtm1@student.school.edu.vn',  passwordHash:'$2a$12$O7maR.RBUdJjpedkDekOBObWj5GNm/waV/izhM9sFDUG3ZK/c0NRe', role:'STUDENT', refId:'cls_qtm1' },
    { id:'usr_sv_udpm1',  email:'sv.udpm1@student.school.edu.vn', passwordHash:'$2a$12$i8LPffn3IrLAOY1AAGmg9OwcPN/DuXNyjJU1K2ja/Dnvnvhbwl7Qm', role:'STUDENT', refId:'cls_udpm1' },
    { id:'usr_sv_tkdh1',  email:'sv.tkdh1@student.school.edu.vn', passwordHash:'$2a$12$yE/D1vQYR/hbwhNFFJhwWuykx8Iit3cDW4odsHCd6GVp49lm95zpm', role:'STUDENT', refId:'cls_tkdh1' },
  ]});
  console.log('✓ users (13)');

  // 13. SCHEDULE VERSIONS
  await prisma.scheduleVersion.createMany({ data: [
    { id:'ver_hk1_k15_draft', versionLabel:'HK1-K15-draft', snapshot:{semester:1,cohort:'K15',total_schedules:8,status:'draft'},   createdAt:new Date('2023-09-29T08:00:00'), createdBy:'usr_admin1' },
    { id:'ver_hk3_k15_final', versionLabel:'HK3-K15-final', snapshot:{semester:3,cohort:'K15',total_schedules:45,status:'final'}, createdAt:new Date('2024-09-04T08:00:00'), createdBy:'usr_admin1' },
    { id:'ver_hk4_k15_final', versionLabel:'HK4-K15-final', snapshot:{semester:4,cohort:'K15',total_schedules:52,status:'final'}, createdAt:new Date('2025-01-24T08:00:00'), createdBy:'usr_admin2' },
    { id:'ver_hk5_k15_v1',    versionLabel:'HK5-K15-v1',    snapshot:{semester:5,cohort:'K15',total_schedules:60,status:'draft',updated:'2025-10-30'}, createdAt:new Date('2025-10-30T08:00:00'), createdBy:'usr_admin2' },
  ]});
  console.log('✓ scheduleVersions (4)');

  console.log('\n✅ seed_patched.sql loaded successfully!');
  console.log('   Admin: admin@school.edu.vn / (existing hash)');
  await prisma.$disconnect();
}

run().catch(e => { console.error('❌', e.message); prisma.$disconnect(); });
