const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// code → nameEn mapping for all 191 subjects
const NAME_EN = {
  // ── IT1xx (shared intro) ─────────────────────────────────────────────────
  'IT101': 'Basic Programming',
  'IT102': 'Introduction to Computer Networks',
  'IT103': 'Computer Architecture (Lab)',
  'IT104': 'Database Management with SQL Server',
  'IT105': 'Applied Graphics',
  'IT106': 'Website Development',

  // ── LMHxx (general / foundational) ──────────────────────────────────────
  'LMH01': 'Political Science',
  'LMH02': 'Law',
  'LMH03': 'Advanced Mathematics',
  'LMH04': 'Soft Skills',
  'LMH05': 'Computer Architecture',
  'LMH06': 'Fundamentals of Vietnamese Culture',
  'LMH07': 'English 1',
  'LMH08': 'English 2',
  'LMH09': 'English 3',

  // ── MHxx (QTM core) ──────────────────────────────────────────────────────
  'MH00007': 'Physical Education',
  'MH01': 'Political Science',
  'MH02': 'Law',
  'MH03': 'Advanced Mathematics',
  'MH04': 'Basic Computer Skills',
  'MH05': 'English 1',
  'MH06': 'National Defense Education',
  'MH07': 'Physical Education',
  'MH08': 'English 2',
  'MH09': 'Office Computing',
  'MH10': 'Computer Architecture',
  'MH11': 'Basic Programming',
  'MH12': 'Computer Installation & Maintenance',
  'MH13': 'Introduction to Computer Networks',
  'MH14': 'Wireless Network Technology',
  'MH15': 'Electronics Fundamentals',
  'MH16': 'Technical English 1',
  'MH17': 'Database',
  'MH18': 'Object-Oriented Programming',
  'MH19': 'Data Structures & Algorithms',
  'MH20': 'Website Design',
  'MH21': 'Windows Network Administration',
  'MH22': 'Industry Internship',
  'MH23': 'Technical English 2',
  'MH24': 'SQL Server Database Management',
  'MH25': 'Network Programming',
  'MH26': 'Web Server & Mail Server Administration',
  'MH27': 'Systems Analysis & Design',
  'MH28': 'Linux Operating System',
  'MH29': 'Professional Internship',
  'MH30': 'Firewall Systems',
  'MH31': 'Soft Skills',
  'MH32': 'Website Development with Open Source CMS',
  'MH33': 'Linux Network Administration',
  'MH34': 'Network System Maintenance',
  'MH35': 'Network Security',
  'MH36': 'LAN Design & Implementation',
  'MH37': 'Data Transmission Techniques',
  'MH38': 'Graduation Internship',
  'MH39': 'Graduation Project / Exam',

  // ── QT2xx (QTM — new curriculum) ─────────────────────────────────────────
  'QT201': 'Linux Operating System',
  'QT202': 'Windows Server Network Administration',
  'QT203': 'Linux Network Administration',
  'QT204': 'Network Security',
  'QT205': 'Network Programming',
  'QT206': 'Wireless Network Technology',
  'QT207': 'LAN Design & Implementation',
  'QT208': 'Computer System Maintenance',
  'QT209': 'Internet of Things (IoT)',
  'QT210': 'Network Device Installation',
  'QT211': 'Windows Operating System',
  'QT212': 'System Security',
  'QT213': 'Cloud & Firewall Administration',
  'QT214': 'Website Development with Open Source Software',

  // ── LT-MHxx (LTMT — old curriculum) ──────────────────────────────────────
  'LT-MH15': 'Database (LTMT)',
  'LT-MH17': 'Programming Techniques',
  'LT-MH18': 'Microsoft Access Database Management',
  'LT-MH19': 'Data Structures & Algorithms',
  'LT-MH20': 'Object-Oriented Programming',
  'LT-MH21': 'C# Programming',
  'LT-MH22': 'Introductory Internship (LTMT)',
  'LT-MH23': 'Technical English 2 (LTMT)',
  'LT-MH24': 'SQL Server Database Management',
  'LT-MH25': 'Service Programming',
  'LT-MH26': 'Introduction to Software Engineering',
  'LT-MH27': 'Systems Analysis & Design',
  'LT-MH28': 'Website Design (LTMT)',
  'LT-MH29': 'Linux Operating System (LTMT)',
  'LT-MH30': 'Professional Internship (LTMT)',
  'LT-MH31': 'Soft Skills (LTMT)',
  'LT-MH32': 'PHP.NET Programming',
  'LT-MH33': 'Mobile Application Development',
  'LT-MH34': 'Linux Programming',
  'LT-MH35': 'Management Software Development',
  'LT-MH36': 'XML Programming',
  'LT-MH37': 'Graduation Internship (LTMT)',
  'LT-MH38': 'Graduation Project (LTMT)',

  // ── LT2xx (LTMT — new curriculum) ────────────────────────────────────────
  'LT201': 'C/C++ Programming',
  'LT202': 'Object-Oriented Programming (Java)',
  'LT203': 'C# Programming',
  'LT204': 'PHP Programming',
  'LT205': 'Python Programming',
  'LT206': 'Database',
  'LT207': 'Systems Analysis & Design',
  'LT208': 'Management Software Development',
  'LT209': 'Mobile Application Development',
  'LT210': 'Web Service Programming',
  'LT211': 'Data Structures & Algorithms',
  'LT212': 'Software Engineering',
  'LT213': 'IT Project Management',
  'LT214': 'Information Security',
  'LT215': 'AI Applications in Programming',
  'LT216': 'Website Administration with Frameworks',
  'LT217': 'Foundation Internship',
  'LT218': 'Graduation Project',

  // ── UD-MHxx (UDPM — old curriculum) ──────────────────────────────────────
  'UD-MH09': 'Word Processing',
  'UD-MH14': 'Excel Spreadsheet',
  'UD-MH15': 'Technical English 1 (UDPM)',
  'UD-MH16': 'Database (UDPM)',
  'UD-MH17': 'Windows Network Administration (UDPM)',
  'UD-MH18': 'Microsoft Access Database Management (UDPM)',
  'UD-MH19': 'Data Structures & Algorithms (UDPM)',
  'UD-MH20': 'Website Development with HTML5',
  'UD-MH21': 'Introductory Internship (UDPM)',
  'UD-MH22': 'Technical English 2 (UDPM)',
  'UD-MH23': 'Image Processing',
  'UD-MH24': 'SQL Server Database Management (UDPM)',
  'UD-MH25': 'Graphic Design with Corel Draw',
  'UD-MH26': 'Web Programming',
  'UD-MH27': 'Systems Analysis & Design (UDPM)',
  'UD-MH28': 'Linux Operating System (UDPM)',
  'UD-MH29': 'Professional Internship (UDPM)',
  'UD-MH30': 'General Accounting',
  'UD-MH31': 'Soft Skills (UDPM)',
  'UD-MH32': 'Information Security',
  'UD-MH33': 'Website Development with Open Source CMS (UDPM)',
  'UD-MH34': 'IT Project Management',
  'UD-MH35': 'Business Organization & Management',
  'UD-MH36': 'Management Software Development (UDPM)',
  'UD-MH37': 'Presentation Design',
  'UD-MH38': 'Graduation Internship (UDPM)',
  'UD-MH39': 'Graduation Project / Exam (UDPM)',

  // ── UD2xx (UDPM — new curriculum) ────────────────────────────────────────
  'UD201': 'Advanced Database',
  'UD202': 'Software Analysis & Design',
  'UD203': 'C# Application Programming',
  'UD204': 'Java Web Programming',
  'UD205': 'Advanced PHP Programming',
  'UD206': 'Advanced Website Development',
  'UD207': 'Mobile Application Programming',
  'UD208': 'Software Project Management',
  'UD209': 'Software Testing',
  'UD210': 'Application Security',
  'UD211': 'Applied Artificial Intelligence',
  'UD212': 'Graduation Project',

  // ── TK-MHxx (TKĐH — old curriculum) ──────────────────────────────────────
  'TK-MH09': 'Office Computing (TKĐH)',
  'TK-MH10': 'Computer Architecture (TKĐH)',
  'TK-MH11': 'Basic Programming (TKĐH)',
  'TK-MH12': 'Basic Drawing',
  'TK-MH13': 'History of Fine Arts',
  'TK-MH14': 'Graphic Design with Corel Draw',
  'TK-MH15': 'Color Science & Nature Study',
  'TK-MH16': 'Technical English 1 (TKĐH)',
  'TK-MH17': 'Database (TKĐH)',
  'TK-MH18': 'Basic Graphic Design',
  'TK-MH19': 'Applied Drawing',
  'TK-MH20': 'Advanced Corel Draw',
  'TK-MH21': 'Fundamentals of 2D Composition',
  'TK-MH22': '2D Modeling (Illustrator)',
  'TK-MH23': 'Introductory Internship (TKĐH)',
  'TK-MH24': 'Technical English 2 (TKĐH)',
  'TK-MH25': 'Graphic Design for Industry & Commerce',
  'TK-MH26': 'Desktop Publishing',
  'TK-MH27': 'Website Design (TKĐH)',
  'TK-MH28': 'Image Processing (TKĐH)',
  'TK-MH29': 'Fundamentals of 3D Composition',
  'TK-MH30': 'Professional Internship (TKĐH)',
  'TK-MH31': 'Soft Skills (TKĐH)',
  'TK-MH32': 'Peripheral Devices',
  'TK-MH33': 'Comprehensive Graphic Design',
  'TK-MH34': 'Video Production',
  'TK-MH35': 'Flash',
  'TK-MH36': 'Graphic Design for Cultural Arts',
  'TK-MH37': 'Advanced Image Processing',
  'TK-MH38': 'Graduation Internship (TKĐH)',
  'TK-MH39': 'Graduation Project / Exam (TKĐH)',

  // ── TK2xx (TKĐH — new curriculum) ────────────────────────────────────────
  'TK201': 'Basic Drawing',
  'TK202': 'Fundamentals of Composition',
  'TK203': '2D Modeling',
  'TK204': 'Corel Draw',
  'TK205': 'Photoshop / Image Processing',
  'TK206': 'Illustrator',
  'TK207': 'Motion Graphics (Flash/Animate)',
  'TK208': '3D Graphics (3ds Max)',
  'TK209': 'Website UI/UX Design',
  'TK210': 'Product Label & Packaging Design',
  'TK211': 'Advertising Graphic Design',
  'TK212': 'Video Production (Premiere/After Effects)',
  'TK213': 'Print Layout Design',
  'TK214': 'Brand Identity Design',
  'TK215': 'Photography Techniques',
  'TK216': 'AI Applications in Graphic Design',
  'TK217': 'Graduation Project',
};

async function main() {
  let updated = 0;
  let notFound = 0;

  for (const [code, nameEn] of Object.entries(NAME_EN)) {
    const result = await prisma.subject.updateMany({
      where: { code },
      data: { nameEn },
    });
    if (result.count > 0) {
      updated++;
    } else {
      console.warn(`  NOT FOUND: ${code}`);
      notFound++;
    }
  }

  console.log(`\nDone. Updated: ${updated} | Not found: ${notFound} | Total mapped: ${Object.keys(NAME_EN).length}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
